from __future__ import annotations

from typing import Final


def _field(name: str, field_type: str, mode: str = "NULLABLE") -> dict[str, str]:
    return {"name": name, "type": field_type, "mode": mode}


BIGQUERY_TABLES: Final[dict[str, list[dict[str, str]]]] = {
    "raw_sources": [
        _field("source_id", "STRING", "REQUIRED"),
        _field("source_type", "STRING", "REQUIRED"),
        _field("channel", "STRING", "REQUIRED"),
        _field("url", "STRING"),
        _field("title", "STRING"),
        _field("raw_text_path", "STRING", "REQUIRED"),
        _field("published_at", "TIMESTAMP"),
        _field("collected_at", "TIMESTAMP", "REQUIRED"),
        _field("checksum", "STRING", "REQUIRED"),
        _field("contains_pii", "BOOL", "REQUIRED"),
    ],
    "mother_entities": [
        _field("entity_id", "STRING", "REQUIRED"),
        _field("entity_type", "STRING", "REQUIRED"),
        _field("name", "STRING", "REQUIRED"),
        _field("normalized_name", "STRING", "REQUIRED"),
        _field("region", "STRING"),
        _field("industry", "STRING"),
        _field("homepage", "STRING"),
        _field("representative", "STRING"),
        _field("contact_email", "STRING"),
        _field("first_seen_at", "TIMESTAMP", "REQUIRED"),
        _field("last_seen_at", "TIMESTAMP", "REQUIRED"),
    ],
    "entity_aliases": [
        _field("alias_id", "STRING", "REQUIRED"),
        _field("entity_id", "STRING", "REQUIRED"),
        _field("alias", "STRING", "REQUIRED"),
        _field("normalized_alias", "STRING", "REQUIRED"),
        _field("source_id", "STRING"),
        _field("created_at", "TIMESTAMP", "REQUIRED"),
    ],
    "entity_resolution_events": [
        _field("event_id", "STRING", "REQUIRED"),
        _field("candidate_entity_id", "STRING", "REQUIRED"),
        _field("matched_entity_id", "STRING"),
        _field("action", "STRING", "REQUIRED"),
        _field("probability", "FLOAT", "REQUIRED"),
        _field("features_json", "STRING", "REQUIRED"),
        _field("rationale", "STRING", "REQUIRED"),
        _field("status", "STRING", "REQUIRED"),
        _field("created_at", "TIMESTAMP", "REQUIRED"),
    ],
    "signals": [
        _field("signal_id", "STRING", "REQUIRED"),
        _field("entity_id", "STRING", "REQUIRED"),
        _field("signal_type", "STRING", "REQUIRED"),
        _field("evidence_text", "STRING", "REQUIRED"),
        _field("source_id", "STRING", "REQUIRED"),
        _field("confidence", "FLOAT", "REQUIRED"),
        _field("tags", "STRING", "REPEATED"),
        _field("detected_at", "TIMESTAMP", "REQUIRED"),
    ],
    "ac_profiles": [
        _field("ac_id", "STRING", "REQUIRED"),
        _field("ac_name", "STRING", "REQUIRED"),
        _field("fund_purpose", "STRING", "REQUIRED"),
        _field("recruiting_area", "STRING"),
        _field("hypothesis_tags", "STRING", "REPEATED"),
        _field("impact_priority", "STRING", "REPEATED"),
        _field("region_preferences", "STRING", "REPEATED"),
        _field("industry_preferences", "STRING", "REPEATED"),
        _field("tech_preferences", "STRING", "REPEATED"),
    ],
    "ac_scores": [
        _field("score_id", "STRING", "REQUIRED"),
        _field("ac_id", "STRING", "REQUIRED"),
        _field("entity_id", "STRING", "REQUIRED"),
        _field("base_score", "FLOAT", "REQUIRED"),
        _field("fund_fit_score", "FLOAT", "REQUIRED"),
        _field("recruiting_fit_score", "FLOAT", "REQUIRED"),
        _field("hypothesis_fit_score", "FLOAT", "REQUIRED"),
        _field("impact_fit_score", "FLOAT", "REQUIRED"),
        _field("total_score", "FLOAT", "REQUIRED"),
        _field("priority_probability", "FLOAT", "REQUIRED"),
        _field("priority_utility", "FLOAT", "REQUIRED"),
        _field("queue_type", "STRING", "REQUIRED"),
        _field("uncertainty", "FLOAT", "REQUIRED"),
        _field("model_version", "STRING", "REQUIRED"),
        _field("rationale", "STRING", "REQUIRED"),
        _field("recommended_action", "STRING", "REQUIRED"),
        _field("scored_at", "TIMESTAMP", "REQUIRED"),
    ],
    "candidate_cards": [
        _field("card_id", "STRING", "REQUIRED"),
        _field("ac_id", "STRING", "REQUIRED"),
        _field("entity_id", "STRING", "REQUIRED"),
        _field("summary", "STRING", "REQUIRED"),
        _field("recommended_action", "STRING", "REQUIRED"),
        _field("queue_type", "STRING", "REQUIRED"),
        _field("status", "STRING", "REQUIRED"),
        _field("created_at", "TIMESTAMP", "REQUIRED"),
    ],
    "reviews": [
        _field("review_id", "STRING", "REQUIRED"),
        _field("card_id", "STRING", "REQUIRED"),
        _field("reviewer", "STRING", "REQUIRED"),
        _field("decision", "STRING", "REQUIRED"),
        _field("memo", "STRING"),
        _field("reviewed_at", "TIMESTAMP", "REQUIRED"),
    ],
    "ac_scoring_coefficients": [
        _field("ac_id", "STRING", "REQUIRED"),
        _field("beta0", "FLOAT", "REQUIRED"),
        _field("fund_fit", "FLOAT", "REQUIRED"),
        _field("recruitment_fit", "FLOAT", "REQUIRED"),
        _field("impact_fit", "FLOAT", "REQUIRED"),
        _field("channel_trust", "FLOAT", "REQUIRED"),
        _field("multi_channel_signal", "FLOAT", "REQUIRED"),
        _field("prior_decision", "FLOAT", "REQUIRED"),
        _field("freshness", "FLOAT", "REQUIRED"),
        _field("risk", "FLOAT", "REQUIRED"),
        _field("sample_count", "INTEGER", "REQUIRED"),
        _field("model_version", "STRING", "REQUIRED"),
        _field("corpus_hash", "STRING", "REQUIRED"),
        _field("updated_at", "TIMESTAMP", "REQUIRED"),
    ],
    "agent_runs": [
        _field("run_id", "STRING", "REQUIRED"),
        _field("job_name", "STRING", "REQUIRED"),
        _field("status", "STRING", "REQUIRED"),
        _field("started_at", "TIMESTAMP", "REQUIRED"),
        _field("finished_at", "TIMESTAMP"),
        _field("input_count", "INTEGER"),
        _field("output_count", "INTEGER"),
        _field("error_message", "STRING"),
    ],
    "sminfo_company_profiles": [
        _field("profile_id", "STRING", "REQUIRED"),
        _field("requested_company", "STRING", "REQUIRED"),
        _field("match_status", "STRING", "REQUIRED"),
        _field("matched_company", "STRING"),
        _field("representative", "STRING"),
        _field("company_type", "STRING"),
        _field("established_at", "STRING"),
        _field("road_address", "STRING"),
        _field("homepage", "STRING"),
        _field("main_products", "STRING"),
        _field("standard_industry", "STRING"),
        _field("info_updated_at", "STRING"),
        _field("latest_financial_year", "STRING"),
        _field("revenue_krw_thousand", "STRING"),
        _field("operating_income_krw_thousand", "STRING"),
        _field("net_income_krw_thousand", "STRING"),
        _field("total_assets_krw_thousand", "STRING"),
        _field("shareholder_composition", "STRING"),
        _field("largest_shareholder", "STRING"),
        _field("largest_shareholder_ratio_pct", "STRING"),
        _field("shareholder_count", "STRING"),
        _field("sminfo_url", "STRING"),
        _field("raw_json", "STRING"),
        _field("error_message", "STRING"),
        _field("collected_at", "TIMESTAMP", "REQUIRED"),
    ],
    "sminfo_enrichment_queue": [
        _field("task_id", "STRING", "REQUIRED"),
        _field("company", "STRING", "REQUIRED"),
        _field("normalized_name", "STRING"),
        _field("representative", "STRING"),
        _field("homepage", "STRING"),
        _field("source_url", "STRING"),
        _field("source_channel", "STRING", "REQUIRED"),
        _field("status", "STRING", "REQUIRED"),
        _field("priority", "INTEGER", "REQUIRED"),
        _field("attempt_count", "INTEGER", "REQUIRED"),
        _field("max_attempts", "INTEGER", "REQUIRED"),
        _field("next_run_at", "TIMESTAMP", "REQUIRED"),
        _field("locked_at", "TIMESTAMP"),
        _field("locked_by", "STRING"),
        _field("last_error", "STRING"),
        _field("last_profile_id", "STRING"),
        _field("created_at", "TIMESTAMP", "REQUIRED"),
        _field("updated_at", "TIMESTAMP", "REQUIRED"),
        _field("completed_at", "TIMESTAMP"),
    ],
    "outreach_email_drafts": [
        _field("outreach_id", "STRING", "REQUIRED"),
        _field("company", "STRING", "REQUIRED"),
        _field("contact_email", "STRING", "REQUIRED"),
        _field("subject", "STRING", "REQUIRED"),
        _field("body_text", "STRING"),
        _field("gmail_draft_id", "STRING"),
        _field("status", "STRING", "REQUIRED"),
        _field("source_url", "STRING"),
        _field("drafted_at", "TIMESTAMP", "REQUIRED"),
        _field("error_message", "STRING"),
    ],
    "kvic_fund_types": [
        _field("fund_code", "STRING", "REQUIRED"),
        _field("fund_name", "STRING", "REQUIRED"),
        _field("source_url", "STRING", "REQUIRED"),
        _field("collected_at", "TIMESTAMP", "REQUIRED"),
    ],
    "kvic_funds": [
        _field("fund_id", "STRING", "REQUIRED"),
        _field("fund_type_code", "STRING", "REQUIRED"),
        _field("year_label", "STRING"),
        _field("fund_year", "INTEGER"),
        _field("field_name", "STRING"),
        _field("manager_name", "STRING", "REQUIRED"),
        _field("association_name", "STRING", "REQUIRED"),
        _field("expires_at", "STRING"),
        _field("amount_raw", "STRING"),
        _field("commitment_raw", "STRING"),
        _field("amount_eok", "FLOAT"),
        _field("commitment_eok", "FLOAT"),
        _field("is_active", "BOOL", "REQUIRED"),
        _field("source_url", "STRING", "REQUIRED"),
        _field("raw_json", "STRING", "REQUIRED"),
        _field("collected_at", "TIMESTAMP", "REQUIRED"),
    ],
    "kvic_fund_descriptions": [
        _field("fund_id", "STRING", "REQUIRED"),
        _field("description", "STRING"),
        _field("source_title", "STRING"),
        _field("source_url", "STRING"),
        _field("source_snippet", "STRING"),
        _field("search_query", "STRING"),
        _field("status", "STRING", "REQUIRED"),
        _field("error_message", "STRING"),
        _field("collected_at", "TIMESTAMP", "REQUIRED"),
        _field("updated_at", "TIMESTAMP", "REQUIRED"),
    ],
    "kvic_investor_managers": [
        _field("manager_id", "STRING", "REQUIRED"),
        _field("manager_name", "STRING", "REQUIRED"),
        _field("total_fund_count", "INTEGER", "REQUIRED"),
        _field("active_fund_count", "INTEGER", "REQUIRED"),
        _field("total_amount_eok", "FLOAT"),
        _field("active_amount_eok", "FLOAT"),
        _field("total_commitment_eok", "FLOAT"),
        _field("active_commitment_eok", "FLOAT"),
        _field("fund_fields", "STRING", "REPEATED"),
        _field("representative_funds", "STRING", "REPEATED"),
        _field("profile_tags", "STRING", "REPEATED"),
        _field("latest_fund_year", "INTEGER"),
        _field("next_expiry_at", "STRING"),
        _field("latest_expiry_at", "STRING"),
        _field("collected_at", "TIMESTAMP", "REQUIRED"),
    ],
    "investor_external_profiles": [
        _field("manager_id", "STRING", "REQUIRED"),
        _field("manager_name", "STRING", "REQUIRED"),
        _field("external_aum_eok", "FLOAT"),
        _field("external_fund_count", "INTEGER"),
        _field("external_cumulative_investment_eok", "FLOAT"),
        _field("description", "STRING"),
        _field("evidence_title", "STRING"),
        _field("evidence_url", "STRING"),
        _field("evidence_snippet", "STRING"),
        _field("search_query", "STRING"),
        _field("status", "STRING", "REQUIRED"),
        _field("confidence", "FLOAT"),
        _field("raw_json", "STRING"),
        _field("error_message", "STRING"),
        _field("collected_at", "TIMESTAMP", "REQUIRED"),
        _field("updated_at", "TIMESTAMP", "REQUIRED"),
    ],
    "kvic_sync_state": [
        _field("state_key", "STRING", "REQUIRED"),
        _field("latest_success_at", "TIMESTAMP"),
        _field("status", "STRING", "REQUIRED"),
        _field("fund_type_count", "INTEGER", "REQUIRED"),
        _field("fund_count", "INTEGER", "REQUIRED"),
        _field("manager_count", "INTEGER", "REQUIRED"),
        _field("skipped_reason", "STRING"),
        _field("updated_at", "TIMESTAMP", "REQUIRED"),
    ],
}


def table_field_names(table_name: str) -> set[str]:
    return {field["name"] for field in BIGQUERY_TABLES[table_name]}
